### ISSUE TITLE
No longer working in Next.js 11

### ISSUE THREAD

**Issue by mattjis** [jeremybarbet/next-react-svg#11]
I'm using version 1.1.3

The error is:
```
./vectors/logos/original.svg
TypeError: unsupported file type: undefined (file: undefined)
````

**Comment by KasperAndersson** [comment]
I've encountered the same issue, after updating to Next 11.

next.config.js looks like this:
```
module.exports =
	plugins([
		[images, { exclude: path.resolve(__dirname, 'src/assets/svg') }],
		[reactSvg, { include: path.resolve(__dirname, 'src/assets/svg') }]
	],
	nextConfig
);
```

**Comment by abenz1267** [comment]
Seems to be related to Webpack 5.

**Comment by mattjis** [comment]
@abenz1267 I don't think so. It worked fine in previous versions of Next with Webpack 5 enabled.

**Comment by abenz1267** [comment]
Try running with webpack 4, it works. SVGR has the same problem.

**Comment by KasperAndersson** [comment]
The issue is related to Next 11, https://github.com/vercel/next.js/issues/26130

**Comment by mattjis** [comment]
This issue is fixed in Next.js 11.0.1 which is currently in pre-release. You can update your package.json with `"next": "^11.0.1-canary.5"` if you're needing a fix asap.
