### ISSUE TITLE
Update README regarding nextjs 11+

### ISSUE THREAD

**Issue by akafaneh** [jeremybarbet/next-react-svg#12]
Faced an issue with `Nextjs > 11 < 11.0.1` (anything else work fine)
But if you are using `11.0.1 =<`  
adding `/// <reference types="next-react-svg" />` to `next-env.d.ts` won't work as the file will regenerated and [they recommend not to edit it anyway](https://nextjs.org/docs/basic-features/typescript#existing-projects).

The way to do it now is by creating `custom.d.ts` file, referencing `/// <reference types="next-react-svg" />` in it and adding the file to `tsconfig.json` `include` array

**Comment by jeremybarbet** [comment]
Closed by https://github.com/jeremybarbet/next-react-svg/commit/f4ec69297b0d9c39afec360cc8035749c646e1d4
