### ISSUE TITLE
not working with next-compose-plugin

### ISSUE THREAD

**Issue by mvahedii** [jeremybarbet/next-react-svg#7]
Hi
when use next-react-svg and some plugins with next-compose-plugin, It only works when it is the last member of the array.
Like the example below: 
```
// next.config.js 

module.exports = withPlugins(
  [
    withBundleAnalyzer,
    [
      withPWA,
      {
        pwa: {
          dest: 'public',
          disable: false,
          register: true,
          scope: '/',
          sw: 'service-worker.js',
        },
      },
    ],
    withTM,
    [
      withReactSvg,
      {
        include: path.resolve(__dirname, 'src/assets'),
        webpack(config, options) {
          return config;
        },
      },
    ],
    withImages,
  ],
  nextConfig,
);
```

But in this case next-pwa not working !!!
And if it is not the last member of the array (next-compose-plugin) then the error returns (interval server error 500)

**Comment by jeremybarbet** [comment]
I have been using it in many projects this way and never got a server error: https://github.com/ueno-llc/ueno-next-starter/blob/master/next.config.js#L53-L71

It might be related to your next.js version or another plugin/version conflicting somehow.
